In [3]:
pwd()

"D:\\drbha"

In [4]:
cd("sem3_iitb_material/ee325/assignments/assignment1")

In [5]:
pwd()

"D:\\drbha\\sem3_iitb_material\\ee325\\assignments\\assignment1"

In [17]:
f = open("Assignment 1/hw1a.txt")

IOStream(<file Assignment 1/hw1a.txt>)

In [18]:
nums=[]

Any[]

In [19]:
for l in eachline(f)
    push!(nums, parse(Float64, l))
end

In [20]:
size(nums)

(10000,)

In [23]:
for num in nums
    println(num)
    break
end

117.94770603227657


In [84]:
list_of_k=[10, 20, 50, 100, 200]
num_iters=50

50

In [85]:
sums=zeros(length(list_of_k), 3)

5×3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [86]:
for iter in 1:num_iters
    for i in 1:length(list_of_k)
        k = list_of_k[i]
        start_pos = rand(0:length(nums)-k)
        for j in 1:k
            sums[i, 1]+= nums[j]
            sums[i, 2]+= nums[start_pos + j]
            sums[i, 3]+= nums[rand(1:length(nums))]
        end
    end
end

In [87]:
sums

5×3 Array{Float64,2}:
  61851.3         59357.1         60414.0
 122186.0        120672.0        121050.0
 304321.0        301838.0        300326.0
 605911.0        601366.0        602492.0
      1.19706e6       1.20118e6       1.199e6

In [88]:
for i in 1:length(list_of_k)
    sums[i, :]/=list_of_k[i]
end

In [89]:
sums

5×3 Array{Float64,2}:
 6185.13  5935.71  6041.4
 6109.31  6033.59  6052.5
 6086.42  6036.76  6006.52
 6059.11  6013.66  6024.92
 5985.3   6005.88  5994.98